import type { AppLocale } from '../../app/i18n';
import type { QuestionRole } from '../secret-file';

type DetailTitle = Readonly<Record<QuestionRole, string>>;

const shared = (title: string): DetailTitle => ({ active: title, passive: title });
const paired = (active: string, passive: string): DetailTitle => ({ active, passive });

/*
 * A detail title is a compact scan label, not a compressed copy of its
 * description. Most source labels already name one unambiguous interaction
 * and can be reused on both sides. This catalogue records only the rows for
 * which that would combine, reverse, or otherwise blur the two directions.
 */
const overrides: Partial<Record<AppLocale, Readonly<Record<string, DetailTitle>>>> = {
  'zh-Hant': {
    // 疼痛刺激
    'detail-pain_stimulation-1jrzewy': paired('輕度咬人', '輕度被咬'),
    'detail-pain_stimulation-j9milm': paired('重度咬人', '重度被咬'),

    // 服侍與管教
    'detail-service-1nx0nqc': paired('接受接送', '接送對方'),
    'detail-service-15yxo0r': paired('接受性服侍', '提供性服侍'),
    'detail-discipline-11uedoh': paired('要求寫日記', '撰寫日記'),
    'detail-discipline-11sxnh8': paired('要求寫心得', '撰寫心得'),
    'detail-discipline-mrnfh0': paired('指派任務', '執行指定任務'),
    'detail-discipline-1h3vvc3': paired('訓誡不當行為', '接受訓誡'),
    'detail-discipline-7ki0ex': paired('指定學習項目', '學習指定項目'),
    'detail-discipline-s0l9h0': paired('制定儀式', '執行儀式'),

    // 性互動與肛門互動
    'detail-sexual_interaction-filrqn': paired('射在對方口中', '口中接受射精'),
    'detail-sexual_interaction-1rt5tu9': paired('射在對方臉上', '臉上接受射精'),
    'detail-sexual_interaction-1ue4af6': paired('射在對方胸部', '胸部接受射精'),
    'detail-sexual_interaction-tvmpfz': paired('射在對方陰道', '陰道接受射精'),
    'detail-sexual_interaction-dsyi29': paired('射在對方肛門', '肛門接受射精'),
    'detail-sexual_interaction-29csl5': paired('射在對方頭髮', '頭髮接受射精'),
    'detail-sexual_interaction-qk9oti': paired('要求吞精', '吞精'),
    'detail-sexual_interaction-ik3j9u': paired('要求食用含精食物', '食用含精食物'),
    'detail-sexual_interaction-jfpa5h': paired('引導潮吹', '潮吹'),
    'detail-sexual_interaction-8jcyoj': paired('使對方高潮', '持續被刺激至高潮'),
    'detail-sexual_interaction-w99mgx': paired('要求自慰展示', '自慰展示'),
    'detail-sexual_interaction-1sl20mr': paired('性玩具刺激對方', '接受性玩具刺激'),
    'detail-sexual_interaction-1xo6keo': paired('尿道棒調教對方', '接受尿道棒調教'),
    'detail-sexual_interaction-6pp140': paired('控制跳蛋', '交出跳蛋控制權'),
    'detail-sexual_interaction-flhbf2': paired('要求公共穿跳蛋', '公共穿跳蛋'),
    'detail-anal_interaction-12ghyy9': paired('為對方灌腸', '接受灌腸'),
    'detail-anal_interaction-gwnjaf': paired('接受舔肛服務', '提供舔肛服務'),

    // 多人、奴隸與寵物情境
    'detail-multi_party_interaction-jy04v5': paired('一主多奴／寵・主', '一主多奴／寵・奴／寵'),
    'detail-multi_party_interaction-1retpvp': paired('多主一奴／寵・主', '多主一奴／寵・奴／寵'),
    'detail-multi_party_interaction-1p23a5n': paired('短期交予第三人', '短期被交予第三人'),
    'detail-multi_party_interaction-18qgi5': paired('長期交予第三人', '長期被交予第三人'),
    'detail-multi_party_interaction-8rm4og': paired('特定情況交予第三人', '特定情況被交予第三人'),
    'detail-enslavement-8sl7b1': paired('給予奴隸項圈', '接受奴隸項圈'),
    'detail-enslavement-w3wrxl': paired('關入奴隸籠', '被關入奴隸籠'),
    'detail-pet_play-52x52j': paired('給予寵物項圈', '接受寵物項圈'),
    'detail-pet_play-iua2gj': paired('關入寵物籠', '被關入寵物籠'),

    // 角色扮演：先把角色名稱和角色方向拆開，避免同時把兩個位置塞進標題。
    'detail-role_play-j6rqh7': shared('小寶寶角色'),
    'detail-role_play-1hqqab2': shared('小孩角色'),
    'detail-role_play-1b6vck1': shared('青少年角色'),
    'detail-role_play-1bf86f7': shared('老年人角色'),
    'detail-role_play-1qg4s3q': shared('人偶／娃娃角色'),
    'detail-role_play-1i9t0en': shared('主僕情境'),
    'detail-role_play-1n9uevy': shared('上司／下屬情境'),
    'detail-role_play-kodrud': shared('醫護／病患情境'),
    'detail-role_play-1gts3i7': shared('獄卒／服刑人情境'),
    'detail-role_play-vepd7q': shared('老師／學生情境'),
    'detail-role_play-1virdb': shared('父母／兒女情境'),
    'detail-role_play-pyo1lh': shared('尿布情境'),

    // 物化、暴露與影像
    'detail-objectification-1l6nra5': paired('把對方當椅子', '作為椅子'),
    'detail-objectification-1nqioit': paired('把對方當沙發', '作為沙發'),
    'detail-objectification-6z8u5c': paired('把對方當踏腳墊', '作為踏腳墊'),
    'detail-objectification-gmtfv3': paired('把對方當花瓶', '作為花瓶'),
    'detail-objectification-1xfrg59': paired('把對方當衣架', '作為衣架'),
    'detail-objectification-11fzq08': paired('把對方當人偶', '作為人偶'),
    'detail-objectification-ydg8ls': paired('把對方當菸灰缸', '作為菸灰缸'),
    'detail-objectification-15peili': paired('把對方當餐盤或碗', '作為餐盤或碗'),
    'detail-objectification-18d3dxj': paired('把對方當自慰套', '作為自慰套'),
    'detail-objectification-gg0tot': paired('把對方當假陽具', '作為假陽具'),
    'detail-objectification-11y1b4u': paired('將對方設為交易資產', '作為交易資產'),
    'detail-exposure-yrd6oh': paired('要求在自己面前暴露', '在對方面前暴露'),
    'detail-exposure-84q67p': paired('要求在朋友面前暴露', '在朋友面前暴露'),
    'detail-exposure-1c953fq': paired('要求在陌生人面前暴露', '在陌生人面前暴露'),
    'detail-exposure-cf5jn6': paired('要求在私人空間暴露', '在私人空間暴露'),
    'detail-exposure-jg19zi': paired('要求在公共空間暴露', '在公共空間暴露'),
    'detail-exposure-14ngx9f': paired('觀看性愛過程', '被觀看性愛過程'),
    'detail-exposure-iztub': paired('要求上半身暴露', '上半身暴露'),
    'detail-exposure-lc5lxg': paired('要求下半身暴露', '下半身暴露'),
    'detail-exposure-rhnyao': paired('要求外出不穿內衣褲', '外出不穿內衣褲'),
    'detail-exposure-1on1gyu': paired('要求公共自慰', '公共自慰'),
    'detail-image_recording-wr9mg2': paired('拍攝裸體', '裸體被拍攝'),
    'detail-image_recording-pottfn': paired('拍攝性愛過程', '性愛過程被拍攝'),
    'detail-image_recording-ijadox': paired('拍攝調教過程', '調教過程被拍攝'),
    'detail-image_recording-xuxzia': paired('要求傳送私密影像', '傳送私密影像'),
    'detail-image_recording-1c6bdpw': paired('公開對方私密影像', '私密影像被公開'),
    'detail-image_recording-1942hqe': paired('用私密影像自慰', '私密影像被用於自慰'),
    'detail-image_recording-1ie3kyu': paired('使用對方裝置拍攝', '自己的裝置被用於拍攝'),
    'detail-image_recording-r9zfxi': paired('用自己的裝置拍攝', '被對方用其裝置拍攝'),
    'detail-image_recording-16hzzoq': paired('製作身體影像紀錄', '接受身體影像紀錄'),

    // 排泄與行為限制
    'detail-excretion-10mgbv7': paired('在對方身上淋尿', '被淋尿'),
    'detail-excretion-18pmjci': paired('在對方頭部淋尿', '頭部被淋尿'),
    'detail-excretion-d0tfsd': paired('要求飲尿', '飲尿'),
    'detail-excretion-bz8baf': paired('要求碰觸排泄物', '碰觸排泄物'),
    'detail-excretion-1d9pfly': paired('要求食用排泄物', '食用排泄物'),
    'detail-excretion-1x972yx': paired('要求用排泄物自慰', '用排泄物自慰'),
    'detail-excretion-4yx1it': paired('讓對方扮演尿壺', '扮演尿壺'),
    'detail-excretion-15e9ike': paired('讓對方扮演便座', '扮演便座'),
    'detail-excretion-36n9ra': paired('觀看排泄展示', '展示排泄'),
    'detail-behavior_restriction-1q2915m': paired('限制自慰', '被限制自慰'),
    'detail-behavior_restriction-10wmuve': paired('限制性愛', '被限制性愛'),
    'detail-behavior_restriction-1v32uv6': paired('限制高潮', '被限制高潮'),
    'detail-behavior_restriction-1qutp1i': paired('限制排泄', '被限制排泄'),
    'detail-behavior_restriction-7yynqx': paired('限制睡眠', '被限制睡眠'),
    'detail-behavior_restriction-p66lsr': paired('限制進食', '被限制進食'),
    'detail-behavior_restriction-p4j1x': paired('限制交友', '被限制交友'),
    'detail-behavior_restriction-1jxhizx': paired('限制說話', '被限制說話'),
    'detail-behavior_restriction-1st1nqk': paired('限制洗澡', '被限制洗澡'),

    // 其他
    'detail-other-cx35l0': paired('掐脖子控制呼吸', '被掐脖子控制呼吸'),
    'detail-other-81imh3': shared('胸部埋壓呼吸控制'),
    'detail-other-12ak8nk': shared('真空袋窒息情境'),
    'detail-other-11372gg': shared('水刑情境'),
    'detail-other-1weofdn': paired('催眠對方', '接受催眠'),
    'detail-other-67684a': shared('食物互動'),
    'detail-other-6t50x3': paired('要求刺青', '接受刺青'),
    'detail-other-1k7dzxy': paired('留下烙印', '接受烙印'),
    'detail-other-cpl0rm': paired('指定服裝', '依指定穿著'),
    'detail-other-967tbj': paired('決定對方飲食', '由對方決定飲食'),
    'detail-other-9c5xzq': paired('要求舔腳', '舔對方的腳'),
    'detail-other-1x8oaxq': paired('要求舔鞋', '舔對方的鞋'),
    'detail-other-yswhyo': paired('踩踏對方身體', '被踩踏身體'),
    'detail-other-1cs7dja': paired('踩踏對方臉部', '被踩踏臉部'),
    'detail-other-1pwrugh': paired('使用灌食器餵食', '接受灌食器餵食'),
    'detail-other-suxt6v': paired('留下吻痕', '被留下吻痕'),
    'detail-other-17kwb61': shared('摔角互動'),
    'detail-other-g75mw6': shared('打架式互動'),
    'detail-other-1q0idds': paired('主導綁架情境', '被綁架情境'),
  },
  'zh-Hans': {
    'detail-pain_stimulation-1jrzewy': paired('轻度咬人', '轻度被咬'),
    'detail-pain_stimulation-j9milm': paired('重度咬人', '重度被咬'),

    'detail-service-1nx0nqc': paired('接受接送', '接送对方'),
    'detail-service-15yxo0r': paired('接受性服务', '提供性服务'),
    'detail-discipline-11uedoh': paired('要求写日记', '撰写日记'),
    'detail-discipline-11sxnh8': paired('要求写心得', '撰写心得'),
    'detail-discipline-mrnfh0': paired('指派任务', '执行指定任务'),
    'detail-discipline-1h3vvc3': paired('训诫不当行为', '接受训诫'),
    'detail-discipline-7ki0ex': paired('指定学习项目', '学习指定项目'),
    'detail-discipline-s0l9h0': paired('制定仪式', '执行仪式'),

    'detail-sexual_interaction-filrqn': paired('射在对方口中', '口中接受射精'),
    'detail-sexual_interaction-1rt5tu9': paired('射在对方脸上', '脸上接受射精'),
    'detail-sexual_interaction-1ue4af6': paired('射在对方胸部', '胸部接受射精'),
    'detail-sexual_interaction-tvmpfz': paired('射在对方阴道', '阴道接受射精'),
    'detail-sexual_interaction-dsyi29': paired('射在对方肛门', '肛门接受射精'),
    'detail-sexual_interaction-29csl5': paired('射在对方头发', '头发接受射精'),
    'detail-sexual_interaction-qk9oti': paired('要求吞精', '吞精'),
    'detail-sexual_interaction-ik3j9u': paired('要求食用含精食物', '食用含精食物'),
    'detail-sexual_interaction-jfpa5h': paired('引导潮吹', '潮吹'),
    'detail-sexual_interaction-8jcyoj': paired('使对方高潮', '持续被刺激至高潮'),
    'detail-sexual_interaction-w99mgx': paired('要求自慰展示', '自慰展示'),
    'detail-sexual_interaction-1sl20mr': paired('用性玩具刺激对方', '接受性玩具刺激'),
    'detail-sexual_interaction-1xo6keo': paired('用尿道棒调教对方', '接受尿道棒调教'),
    'detail-sexual_interaction-6pp140': paired('控制跳蛋', '交出跳蛋控制权'),
    'detail-sexual_interaction-flhbf2': paired('要求在公共场所穿跳蛋', '在公共场所穿跳蛋'),
    'detail-anal_interaction-12ghyy9': paired('为对方灌肠', '接受灌肠'),
    'detail-anal_interaction-gwnjaf': paired('接受舔肛服务', '提供舔肛服务'),

    'detail-multi_party_interaction-jy04v5': paired('一主多奴／宠・主', '一主多奴／宠・奴／宠'),
    'detail-multi_party_interaction-1retpvp': paired('多主一奴／宠・主', '多主一奴／宠・奴／宠'),
    'detail-multi_party_interaction-1p23a5n': paired('短期交给第三人', '短期被交给第三人'),
    'detail-multi_party_interaction-18qgi5': paired('长期交给第三人', '长期被交给第三人'),
    'detail-multi_party_interaction-8rm4og': paired('特定情况交给第三人', '特定情况被交给第三人'),
    'detail-enslavement-8sl7b1': paired('给予奴隶项圈', '接受奴隶项圈'),
    'detail-enslavement-w3wrxl': paired('关入奴隶笼', '被关入奴隶笼'),
    'detail-pet_play-52x52j': paired('给予宠物项圈', '接受宠物项圈'),
    'detail-pet_play-iua2gj': paired('关入宠物笼', '被关入宠物笼'),

    'detail-role_play-j6rqh7': shared('小宝宝角色'),
    'detail-role_play-1hqqab2': shared('小孩角色'),
    'detail-role_play-1b6vck1': shared('青少年角色'),
    'detail-role_play-1bf86f7': shared('老年人角色'),
    'detail-role_play-1qg4s3q': shared('人偶／娃娃角色'),
    'detail-role_play-1i9t0en': shared('主仆情境'),
    'detail-role_play-1n9uevy': shared('上司／下属情境'),
    'detail-role_play-kodrud': shared('医护／病患情境'),
    'detail-role_play-1gts3i7': shared('狱卒／服刑人情境'),
    'detail-role_play-vepd7q': shared('老师／学生情境'),
    'detail-role_play-1virdb': shared('父母／儿女情境'),
    'detail-role_play-pyo1lh': shared('尿布情境'),

    'detail-objectification-1l6nra5': paired('把对方当椅子', '作为椅子'),
    'detail-objectification-1nqioit': paired('把对方当沙发', '作为沙发'),
    'detail-objectification-6z8u5c': paired('把对方当脚垫', '作为脚垫'),
    'detail-objectification-gmtfv3': paired('把对方当花瓶', '作为花瓶'),
    'detail-objectification-1xfrg59': paired('把对方当衣架', '作为衣架'),
    'detail-objectification-11fzq08': paired('把对方当人偶', '作为人偶'),
    'detail-objectification-ydg8ls': paired('把对方当烟灰缸', '作为烟灰缸'),
    'detail-objectification-15peili': paired('把对方当餐盘或碗', '作为餐盘或碗'),
    'detail-objectification-18d3dxj': paired('把对方当自慰套', '作为自慰套'),
    'detail-objectification-gg0tot': paired('把对方当假阳具', '作为假阳具'),
    'detail-objectification-11y1b4u': paired('将对方设为交易资产', '作为交易资产'),
    'detail-exposure-yrd6oh': paired('要求在自己面前暴露', '在对方面前暴露'),
    'detail-exposure-84q67p': paired('要求在朋友面前暴露', '在朋友面前暴露'),
    'detail-exposure-1c953fq': paired('要求在陌生人面前暴露', '在陌生人面前暴露'),
    'detail-exposure-cf5jn6': paired('要求在私人空间暴露', '在私人空间暴露'),
    'detail-exposure-jg19zi': paired('要求在公共空间暴露', '在公共空间暴露'),
    'detail-exposure-14ngx9f': paired('观看性爱过程', '性爱过程被观看'),
    'detail-exposure-iztub': paired('要求上半身暴露', '上半身暴露'),
    'detail-exposure-lc5lxg': paired('要求下半身暴露', '下半身暴露'),
    'detail-exposure-rhnyao': paired('要求外出不穿内衣裤', '外出不穿内衣裤'),
    'detail-exposure-1on1gyu': paired('要求在公共场所自慰', '在公共场所自慰'),
    'detail-image_recording-wr9mg2': paired('拍摄裸体', '裸体被拍摄'),
    'detail-image_recording-pottfn': paired('拍摄性爱过程', '性爱过程被拍摄'),
    'detail-image_recording-ijadox': paired('拍摄调教过程', '调教过程被拍摄'),
    'detail-image_recording-xuxzia': paired('要求发送私密影像', '发送私密影像'),
    'detail-image_recording-1c6bdpw': paired('公开对方私密影像', '私密影像被公开'),
    'detail-image_recording-1942hqe': paired('用私密影像自慰', '私密影像被用于自慰'),
    'detail-image_recording-1ie3kyu': paired('用对方装置拍摄', '自己的装置被用于拍摄'),
    'detail-image_recording-r9zfxi': paired('用自己的装置拍摄', '被对方用其装置拍摄'),
    'detail-image_recording-16hzzoq': paired('制作身体影像记录', '接受身体影像记录'),

    'detail-excretion-10mgbv7': paired('在对方身上淋尿', '被淋尿'),
    'detail-excretion-18pmjci': paired('在对方头部淋尿', '头部被淋尿'),
    'detail-excretion-d0tfsd': paired('要求饮尿', '饮尿'),
    'detail-excretion-bz8baf': paired('要求接触排泄物', '接触排泄物'),
    'detail-excretion-1d9pfly': paired('要求食用排泄物', '食用排泄物'),
    'detail-excretion-1x972yx': paired('要求用排泄物自慰', '用排泄物自慰'),
    'detail-excretion-4yx1it': paired('让对方扮演尿壶', '扮演尿壶'),
    'detail-excretion-15e9ike': paired('让对方扮演便座', '扮演便座'),
    'detail-excretion-36n9ra': paired('观看排泄展示', '展示排泄'),
    'detail-behavior_restriction-1q2915m': paired('限制自慰', '被限制自慰'),
    'detail-behavior_restriction-10wmuve': paired('限制性爱', '被限制性爱'),
    'detail-behavior_restriction-1v32uv6': paired('限制高潮', '被限制高潮'),
    'detail-behavior_restriction-1qutp1i': paired('限制排泄', '被限制排泄'),
    'detail-behavior_restriction-7yynqx': paired('限制睡眠', '被限制睡眠'),
    'detail-behavior_restriction-p66lsr': paired('限制进食', '被限制进食'),
    'detail-behavior_restriction-p4j1x': paired('限制交友', '被限制交友'),
    'detail-behavior_restriction-1jxhizx': paired('限制说话', '被限制说话'),
    'detail-behavior_restriction-1st1nqk': paired('限制洗澡', '被限制洗澡'),

    'detail-other-cx35l0': paired('掐脖子控制呼吸', '被掐脖子控制呼吸'),
    'detail-other-81imh3': shared('胸部压迫呼吸控制'),
    'detail-other-12ak8nk': shared('真空袋窒息情境'),
    'detail-other-11372gg': shared('水刑情境'),
    'detail-other-1weofdn': paired('催眠对方', '接受催眠'),
    'detail-other-67684a': shared('食物互动'),
    'detail-other-6t50x3': paired('要求刺青', '接受刺青'),
    'detail-other-1k7dzxy': paired('留下烙印', '接受烙印'),
    'detail-other-cpl0rm': paired('指定服装', '按指定穿着'),
    'detail-other-967tbj': paired('决定对方饮食', '由对方决定饮食'),
    'detail-other-9c5xzq': paired('要求舔脚', '舔对方的脚'),
    'detail-other-1x8oaxq': paired('要求舔鞋', '舔对方的鞋'),
    'detail-other-yswhyo': paired('踩踏对方身体', '身体被踩踏'),
    'detail-other-1cs7dja': paired('踩踏对方脸部', '脸部被踩踏'),
    'detail-other-1pwrugh': paired('用灌食器喂食', '接受灌食器喂食'),
    'detail-other-suxt6v': paired('留下吻痕', '被留下吻痕'),
    'detail-other-17kwb61': shared('摔角互动'),
    'detail-other-g75mw6': shared('打架式互动'),
    'detail-other-1q0idds': paired('主导绑架情境', '被绑架情境'),
  },
  ja: {
    'detail-pain_stimulation-1jrzewy': paired('軽い噛みつき', '軽く噛まれる'),
    'detail-pain_stimulation-j9milm': paired('強い噛みつき', '強く噛まれる'),

    'detail-service-1nx0nqc': paired('送迎を受ける', '相手を送迎する'),
    'detail-service-15yxo0r': paired('性的奉仕を受ける', '性的奉仕をする'),
    'detail-discipline-11uedoh': paired('日記を書くよう求める', '日記を書く'),
    'detail-discipline-11sxnh8': paired('振り返りを書くよう求める', '振り返りを書く'),
    'detail-discipline-mrnfh0': paired('課題を出す', '指定課題を行う'),
    'detail-discipline-1h3vvc3': paired('不適切な行動を戒める', '戒めを受ける'),
    'detail-discipline-7ki0ex': paired('学習項目を指定する', '指定項目を学ぶ'),
    'detail-discipline-s0l9h0': paired('儀式を定める', '儀式を行う'),

    'detail-sexual_interaction-filrqn': paired('口内に射精する', '口内で射精を受ける'),
    'detail-sexual_interaction-1rt5tu9': paired('顔に射精する', '顔で射精を受ける'),
    'detail-sexual_interaction-1ue4af6': paired('胸に射精する', '胸で射精を受ける'),
    'detail-sexual_interaction-tvmpfz': paired('膣内に射精する', '膣内で射精を受ける'),
    'detail-sexual_interaction-dsyi29': paired('肛門に射精する', '肛門で射精を受ける'),
    'detail-sexual_interaction-29csl5': paired('髪に射精する', '髪で射精を受ける'),
    'detail-sexual_interaction-qk9oti': paired('精液を飲むよう求める', '精液を飲む'),
    'detail-sexual_interaction-ik3j9u': paired('精液入りの食べ物を求める', '精液入りの食べ物を食べる'),
    'detail-sexual_interaction-jfpa5h': paired('潮吹きを促す', '潮吹きする'),
    'detail-sexual_interaction-8jcyoj': paired('相手を絶頂に導く', '刺激され続けて絶頂に達する'),
    'detail-sexual_interaction-w99mgx': paired('自慰を見せるよう求める', '自慰を見せる'),
    'detail-sexual_interaction-1sl20mr': paired('性玩具で相手を刺激する', '性玩具で刺激される'),
    'detail-sexual_interaction-1xo6keo': paired('尿道スティックで調教する', '尿道スティックで調教を受ける'),
    'detail-sexual_interaction-6pp140': paired('バイブを操作する', 'バイブの操作権を渡す'),
    'detail-sexual_interaction-flhbf2': paired('公共の場でバイブを着けるよう求める', '公共の場でバイブを着ける'),
    'detail-anal_interaction-12ghyy9': paired('相手に浣腸する', '浣腸を受ける'),
    'detail-anal_interaction-gwnjaf': paired('アナル舐めを受ける', 'アナル舐めをする'),

    'detail-multi_party_interaction-jy04v5': paired('一主多従・主', '一主多従・従'),
    'detail-multi_party_interaction-1retpvp': paired('多主一従・主', '多主一従・従'),
    'detail-multi_party_interaction-1p23a5n': paired('第三者に短期間預ける', '第三者に短期間預けられる'),
    'detail-multi_party_interaction-18qgi5': paired('第三者に長期間預ける', '第三者に長期間預けられる'),
    'detail-multi_party_interaction-8rm4og': paired('第三者に条件付きで預ける', '第三者に条件付きで預けられる'),
    'detail-enslavement-8sl7b1': paired('奴隷用首輪を渡す', '奴隷用首輪を受け取る'),
    'detail-enslavement-w3wrxl': paired('奴隷用ケージに入れる', '奴隷用ケージに入れられる'),
    'detail-pet_play-52x52j': paired('ペット用首輪を渡す', 'ペット用首輪を受け取る'),
    'detail-pet_play-iua2gj': paired('ペット用ケージに入れる', 'ペット用ケージに入れられる'),

    'detail-role_play-j6rqh7': shared('赤ちゃん役'),
    'detail-role_play-1hqqab2': shared('子ども役'),
    'detail-role_play-1b6vck1': shared('ティーン役'),
    'detail-role_play-1bf86f7': shared('高齢者役'),
    'detail-role_play-1qg4s3q': shared('人形・ドール役'),
    'detail-role_play-1i9t0en': shared('主従シナリオ'),
    'detail-role_play-1n9uevy': shared('上司／部下シナリオ'),
    'detail-role_play-kodrud': shared('医療者／患者シナリオ'),
    'detail-role_play-1gts3i7': shared('看守／服役者シナリオ'),
    'detail-role_play-vepd7q': shared('教師／生徒シナリオ'),
    'detail-role_play-1virdb': shared('親子シナリオ'),
    'detail-role_play-pyo1lh': shared('おむつの場面'),

    'detail-objectification-1l6nra5': paired('相手を椅子として使う', '椅子になる'),
    'detail-objectification-1nqioit': paired('相手をソファとして使う', 'ソファになる'),
    'detail-objectification-6z8u5c': paired('相手を足拭きとして使う', '足拭きになる'),
    'detail-objectification-gmtfv3': paired('相手を花瓶として扱う', '花瓶になる'),
    'detail-objectification-1xfrg59': paired('相手を衣装掛けとして使う', '衣装掛けになる'),
    'detail-objectification-11fzq08': paired('相手を人形として扱う', '人形になる'),
    'detail-objectification-ydg8ls': paired('相手を灰皿として使う', '灰皿になる'),
    'detail-objectification-15peili': paired('相手を皿や器として使う', '皿や器になる'),
    'detail-objectification-18d3dxj': paired('相手をオナホとして使う', 'オナホになる'),
    'detail-objectification-gg0tot': paired('相手をディルドとして使う', 'ディルドになる'),
    'detail-objectification-11y1b4u': paired('相手を取引資産にする', '取引資産になる'),
    'detail-exposure-yrd6oh': paired('自分の前で露出するよう求める', '相手の前で露出する'),
    'detail-exposure-84q67p': paired('友人の前で露出するよう求める', '友人の前で露出する'),
    'detail-exposure-1c953fq': paired('他人の前で露出するよう求める', '他人の前で露出する'),
    'detail-exposure-cf5jn6': paired('私的空間で露出するよう求める', '私的空間で露出する'),
    'detail-exposure-jg19zi': paired('公共空間で露出するよう求める', '公共空間で露出する'),
    'detail-exposure-14ngx9f': paired('性行為を観る', '性行為を見られる'),
    'detail-exposure-iztub': paired('上半身を露出するよう求める', '上半身を露出する'),
    'detail-exposure-lc5lxg': paired('下半身を露出するよう求める', '下半身を露出する'),
    'detail-exposure-rhnyao': paired('下着なしの外出を求める', '下着なしで外出する'),
    'detail-exposure-1on1gyu': paired('公共の場での自慰を求める', '公共の場で自慰する'),
    'detail-image_recording-wr9mg2': paired('裸体を撮影する', '裸体を撮影される'),
    'detail-image_recording-pottfn': paired('性行為を撮影する', '性行為を撮影される'),
    'detail-image_recording-ijadox': paired('調教を撮影する', '調教を撮影される'),
    'detail-image_recording-xuxzia': paired('私的な画像を送るよう求める', '私的な画像を送る'),
    'detail-image_recording-1c6bdpw': paired('相手の私的な画像を公開する', '私的な画像を公開される'),
    'detail-image_recording-1942hqe': paired('私的な画像で自慰する', '私的な画像を自慰に使われる'),
    'detail-image_recording-1ie3kyu': paired('相手の機器で撮影する', '自分の機器を撮影に使われる'),
    'detail-image_recording-r9zfxi': paired('自分の機器で撮影する', '相手の機器で撮影される'),
    'detail-image_recording-16hzzoq': paired('身体の記録画像を作る', '身体の記録画像を作られる'),

    'detail-excretion-10mgbv7': paired('相手の体に排尿する', '体に排尿される'),
    'detail-excretion-18pmjci': paired('相手の頭に排尿する', '頭に排尿される'),
    'detail-excretion-d0tfsd': paired('尿を飲むよう求める', '尿を飲む'),
    'detail-excretion-bz8baf': paired('排泄物に触れるよう求める', '排泄物に触れる'),
    'detail-excretion-1d9pfly': paired('排泄物を食べるよう求める', '排泄物を食べる'),
    'detail-excretion-1x972yx': paired('排泄物で自慰するよう求める', '排泄物で自慰する'),
    'detail-excretion-4yx1it': paired('相手を尿瓶役にする', '尿瓶役になる'),
    'detail-excretion-15e9ike': paired('相手を便座役にする', '便座役になる'),
    'detail-excretion-36n9ra': paired('排泄を観る', '排泄を見せる'),
    'detail-behavior_restriction-1q2915m': paired('自慰を制限する', '自慰を制限される'),
    'detail-behavior_restriction-10wmuve': paired('性行為を制限する', '性行為を制限される'),
    'detail-behavior_restriction-1v32uv6': paired('絶頂を制限する', '絶頂を制限される'),
    'detail-behavior_restriction-1qutp1i': paired('排泄を制限する', '排泄を制限される'),
    'detail-behavior_restriction-7yynqx': paired('睡眠を制限する', '睡眠を制限される'),
    'detail-behavior_restriction-p66lsr': paired('食事を制限する', '食事を制限される'),
    'detail-behavior_restriction-p4j1x': paired('交友を制限する', '交友を制限される'),
    'detail-behavior_restriction-1jxhizx': paired('発話を制限する', '発話を制限される'),
    'detail-behavior_restriction-1st1nqk': paired('入浴を制限する', '入浴を制限される'),

    'detail-other-cx35l0': paired('首を絞めて呼吸を制御する', '首を絞められて呼吸を制御される'),
    'detail-other-81imh3': shared('胸への埋没による呼吸制御'),
    'detail-other-12ak8nk': shared('真空袋での窒息場面'),
    'detail-other-11372gg': shared('水責めの場面'),
    'detail-other-1weofdn': paired('相手を催眠する', '催眠を受ける'),
    'detail-other-67684a': shared('食べ物を使うやりとり'),
    'detail-other-6t50x3': paired('刺青を求める', '刺青を受ける'),
    'detail-other-1k7dzxy': paired('烙印を残す', '烙印を受ける'),
    'detail-other-cpl0rm': paired('服装を指定する', '指定の服を着る'),
    'detail-other-967tbj': paired('相手の食べ物を決める', '食べ物を決められる'),
    'detail-other-9c5xzq': paired('足を舐めるよう求める', '相手の足を舐める'),
    'detail-other-1x8oaxq': paired('靴を舐めるよう求める', '相手の靴を舐める'),
    'detail-other-yswhyo': paired('相手の体を踏む', '体を踏まれる'),
    'detail-other-1cs7dja': paired('相手の顔を踏む', '顔を踏まれる'),
    'detail-other-1pwrugh': paired('フィーダーで給餌する', 'フィーダーで給餌される'),
    'detail-other-suxt6v': paired('キスマークを付ける', 'キスマークを付けられる'),
    'detail-other-17kwb61': shared('レスリング風のやりとり'),
    'detail-other-g75mw6': shared('けんか風のやりとり'),
    'detail-other-1q0idds': paired('誘拐場面を主導する', '誘拐される場面'),
  },
  en: {
    'detail-pain_stimulation-1jrzewy': paired('Light biting', 'Being lightly bitten'),
    'detail-pain_stimulation-j9milm': paired('Intense biting', 'Being intensely bitten'),

    'detail-service-1nx0nqc': paired('Receiving a ride', 'Giving a ride'),
    'detail-service-15yxo0r': paired('Receiving sexual service', 'Providing sexual service'),
    'detail-discipline-11uedoh': paired('Ask for a journal entry', 'Write a journal entry'),
    'detail-discipline-11sxnh8': paired('Ask for a reflection', 'Write a reflection'),
    'detail-discipline-mrnfh0': paired('Assign a task', 'Complete an assigned task'),
    'detail-discipline-1h3vvc3': paired('Correct behaviour', 'Receive correction'),
    'detail-discipline-7ki0ex': paired('Assign a learning topic', 'Study an assigned topic'),
    'detail-discipline-s0l9h0': paired('Set a ritual', 'Carry out a ritual'),

    'detail-sexual_interaction-filrqn': paired('Ejaculate in their mouth', 'Receive ejaculation in the mouth'),
    'detail-sexual_interaction-1rt5tu9': paired('Ejaculate on their face', 'Receive ejaculation on the face'),
    'detail-sexual_interaction-1ue4af6': paired('Ejaculate on their chest', 'Receive ejaculation on the chest'),
    'detail-sexual_interaction-tvmpfz': paired('Ejaculate in their vagina', 'Receive ejaculation in the vagina'),
    'detail-sexual_interaction-dsyi29': paired('Ejaculate at their anus', 'Receive ejaculation at the anus'),
    'detail-sexual_interaction-29csl5': paired('Ejaculate on their hair', 'Receive ejaculation on the hair'),
    'detail-sexual_interaction-qk9oti': paired('Ask them to swallow semen', 'Swallow semen'),
    'detail-sexual_interaction-ik3j9u': paired('Ask them to eat food with semen', 'Eat food with semen'),
    'detail-sexual_interaction-jfpa5h': paired('Encourage squirting', 'Squirting'),
    'detail-sexual_interaction-8jcyoj': paired('Bring them to orgasm', 'Be stimulated to orgasm'),
    'detail-sexual_interaction-w99mgx': paired('Ask for a masturbation display', 'Show masturbation'),
    'detail-sexual_interaction-1sl20mr': paired('Stimulate them with a sex toy', 'Receive sex-toy stimulation'),
    'detail-sexual_interaction-1xo6keo': paired('Use urethral sounding on them', 'Receive urethral sounding'),
    'detail-sexual_interaction-6pp140': paired('Control the vibrator', 'Hand over vibrator control'),
    'detail-sexual_interaction-flhbf2': paired('Ask for a public vibrator', 'Wear a vibrator in public'),
    'detail-anal_interaction-12ghyy9': paired('Give an enema', 'Receive an enema'),
    'detail-anal_interaction-gwnjaf': paired('Receive anal oral service', 'Provide anal oral service'),

    'detail-multi_party_interaction-jy04v5': paired('One master, many submissives — master', 'One master, many submissives — submissive'),
    'detail-multi_party_interaction-1retpvp': paired('Many masters, one submissive — master', 'Many masters, one submissive — submissive'),
    'detail-multi_party_interaction-1p23a5n': paired('Place them with a third person short term', 'Be placed with a third person short term'),
    'detail-multi_party_interaction-18qgi5': paired('Place them with a third person long term', 'Be placed with a third person long term'),
    'detail-multi_party_interaction-8rm4og': paired('Place them with a third person conditionally', 'Be placed with a third person conditionally'),
    'detail-enslavement-8sl7b1': paired('Give a slave collar', 'Receive a slave collar'),
    'detail-enslavement-w3wrxl': paired('Place them in a slave cage', 'Be placed in a slave cage'),
    'detail-pet_play-52x52j': paired('Give a pet collar', 'Receive a pet collar'),
    'detail-pet_play-iua2gj': paired('Place them in a pet cage', 'Be placed in a pet cage'),

    'detail-role_play-j6rqh7': shared('Baby role'),
    'detail-role_play-1hqqab2': shared('Child role'),
    'detail-role_play-1b6vck1': shared('Teen role'),
    'detail-role_play-1bf86f7': shared('Older-adult role'),
    'detail-role_play-1qg4s3q': shared('Doll role'),
    'detail-role_play-1i9t0en': shared('Master–servant scenario'),
    'detail-role_play-1n9uevy': shared('Boss–subordinate scenario'),
    'detail-role_play-kodrud': shared('Medical-worker–patient scenario'),
    'detail-role_play-1gts3i7': shared('Prison-guard–prisoner scenario'),
    'detail-role_play-vepd7q': shared('Teacher–student scenario'),
    'detail-role_play-1virdb': shared('Parent–child scenario'),
    'detail-role_play-pyo1lh': shared('Diaper scenario'),

    'detail-objectification-1l6nra5': paired('Use them as a chair', 'Be a chair'),
    'detail-objectification-1nqioit': paired('Use them as a sofa', 'Be a sofa'),
    'detail-objectification-6z8u5c': paired('Use them as a footstool', 'Be a footstool'),
    'detail-objectification-gmtfv3': paired('Display them as a vase', 'Be a vase'),
    'detail-objectification-1xfrg59': paired('Use them as a clothes rack', 'Be a clothes rack'),
    'detail-objectification-11fzq08': paired('Display them as a doll', 'Be a doll'),
    'detail-objectification-ydg8ls': paired('Use them as an ashtray', 'Be an ashtray'),
    'detail-objectification-15peili': paired('Use them as a plate or bowl', 'Be a plate or bowl'),
    'detail-objectification-18d3dxj': paired('Use them as a masturbator', 'Be a masturbator'),
    'detail-objectification-gg0tot': paired('Use them as a dildo', 'Be a dildo'),
    'detail-objectification-11y1b4u': paired('Treat them as a trade asset', 'Be a trade asset'),
    'detail-exposure-yrd6oh': paired('Ask them to expose themselves to you', 'Expose yourself to them'),
    'detail-exposure-84q67p': paired('Ask them to expose themselves to friends', 'Expose yourself to friends'),
    'detail-exposure-1c953fq': paired('Ask them to expose themselves to strangers', 'Expose yourself to strangers'),
    'detail-exposure-cf5jn6': paired('Ask for exposure in private', 'Expose yourself in private'),
    'detail-exposure-jg19zi': paired('Ask for exposure in public', 'Expose yourself in public'),
    'detail-exposure-14ngx9f': paired('Watch sexual activity', 'Be watched during sexual activity'),
    'detail-exposure-iztub': paired('Ask for upper-body exposure', 'Expose your upper body'),
    'detail-exposure-lc5lxg': paired('Ask for lower-body exposure', 'Expose your lower body'),
    'detail-exposure-rhnyao': paired('Ask them to go out without underwear', 'Go out without underwear'),
    'detail-exposure-1on1gyu': paired('Ask for public masturbation', 'Masturbate in public'),
    'detail-image_recording-wr9mg2': paired('Record nudity', 'Have nudity recorded'),
    'detail-image_recording-pottfn': paired('Record sexual activity', 'Have sexual activity recorded'),
    'detail-image_recording-ijadox': paired('Record training activity', 'Have training activity recorded'),
    'detail-image_recording-xuxzia': paired('Ask for private images', 'Send private images'),
    'detail-image_recording-1c6bdpw': paired('Publish their private images', 'Have private images published'),
    'detail-image_recording-1942hqe': paired('Masturbate with private images', 'Have private images used for masturbation'),
    'detail-image_recording-1ie3kyu': paired('Record with their device', 'Have your device used for recording'),
    'detail-image_recording-r9zfxi': paired('Record with your device', 'Be recorded with their device'),
    'detail-image_recording-16hzzoq': paired('Create a body-image record', 'Have a body-image record made'),

    'detail-excretion-10mgbv7': paired('Urinate on their body', 'Be urinated on'),
    'detail-excretion-18pmjci': paired('Urinate on their head', 'Be urinated on above the head'),
    'detail-excretion-d0tfsd': paired('Ask them to drink urine', 'Drink urine'),
    'detail-excretion-bz8baf': paired('Ask them to touch excrement', 'Touch excrement'),
    'detail-excretion-1d9pfly': paired('Ask them to eat excrement', 'Eat excrement'),
    'detail-excretion-1x972yx': paired('Ask them to masturbate with excrement', 'Masturbate with excrement'),
    'detail-excretion-4yx1it': paired('Make them a urinal', 'Be a urinal'),
    'detail-excretion-15e9ike': paired('Make them a toilet seat', 'Be a toilet seat'),
    'detail-excretion-36n9ra': paired('Watch excretion', 'Show excretion'),
    'detail-behavior_restriction-1q2915m': paired('Restrict masturbation', 'Have masturbation restricted'),
    'detail-behavior_restriction-10wmuve': paired('Restrict sexual activity', 'Have sexual activity restricted'),
    'detail-behavior_restriction-1v32uv6': paired('Restrict orgasm', 'Have orgasm restricted'),
    'detail-behavior_restriction-1qutp1i': paired('Restrict excretion', 'Have excretion restricted'),
    'detail-behavior_restriction-7yynqx': paired('Restrict sleep', 'Have sleep restricted'),
    'detail-behavior_restriction-p66lsr': paired('Restrict eating', 'Have eating restricted'),
    'detail-behavior_restriction-p4j1x': paired('Restrict social contact', 'Have social contact restricted'),
    'detail-behavior_restriction-1jxhizx': paired('Restrict speech', 'Have speech restricted'),
    'detail-behavior_restriction-1st1nqk': paired('Restrict bathing', 'Have bathing restricted'),

    'detail-other-cx35l0': paired('Control breathing by choking', 'Have breathing controlled by choking'),
    'detail-other-81imh3': shared('Breathing control against the chest'),
    'detail-other-12ak8nk': shared('Vacuum-bag asphyxiation scenario'),
    'detail-other-11372gg': shared('Water-torture scenario'),
    'detail-other-1weofdn': paired('Hypnotise them', 'Receive hypnosis'),
    'detail-other-67684a': shared('Food-based interaction'),
    'detail-other-6t50x3': paired('Ask for a tattoo', 'Receive a tattoo'),
    'detail-other-1k7dzxy': paired('Leave a brand', 'Receive a brand'),
    'detail-other-cpl0rm': paired('Specify their clothing', 'Wear specified clothing'),
    'detail-other-967tbj': paired('Decide their food', 'Have food decided for you'),
    'detail-other-9c5xzq': paired('Ask them to lick your feet', 'Lick their feet'),
    'detail-other-1x8oaxq': paired('Ask them to lick your shoes', 'Lick their shoes'),
    'detail-other-yswhyo': paired('Step on their body', 'Have your body stepped on'),
    'detail-other-1cs7dja': paired('Step on their face', 'Have your face stepped on'),
    'detail-other-1pwrugh': paired('Feed with a feeder', 'Be fed with a feeder'),
    'detail-other-suxt6v': paired('Leave a hickey', 'Receive a hickey'),
    'detail-other-17kwb61': shared('Wrestling-style interaction'),
    'detail-other-g75mw6': shared('Fight-style interaction'),
    'detail-other-1q0idds': paired('Lead a kidnapping scenario', 'Be in a kidnapping scenario'),
  },
};

export function getDetailTitle(
  locale: AppLocale,
  detailId: string,
  role: QuestionRole,
  fallback: string,
): string {
  return overrides[locale]?.[detailId]?.[role] ?? fallback;
}
